productName = "kasuri"
version = "0.1.0"
identifier = "jp.sabiz.kasuri"

[build]
beforeDevCommand = "npm run dev"
devUrl = "http://localhost:1420"
beforeBuildCommand = "npm run build"
frontendDist = "../build"

[app]
# [app.security]
# csp = null

[[app.windows]]
title = "kasuri"
width = 800
height = 600

[bundle]
active = true
targets = "all"
icon = [
    "icons/32x32.png",
    "icons/128x128.png",
    "icons/128x128@2x.png",
    "icons/icon.icns",
    "icons/icon.ico",
]
