productName = "KASURI"
version = "0.2.0"
identifier = "jp.sabiz.kasuri"

[build]
beforeDevCommand = "npm run dev"
devUrl = "http://localhost:1420"
beforeBuildCommand = "npm run build"
frontendDist = "../build"

[app]
withGlobalTauri = false

[app.security]
capabilities = ["default"]
csp = "default-src 'self'; img-src 'self' data: asset: http://asset.localhost; style-src 'self' 'unsafe-inline'; connect-src 'self' http://ipc.localhost https://api.iconify.design"

[app.security.assetProtocol]
enable = true
[app.security.assetProtocol.scope]
allow = ["$APPCACHE/*.png"]

[app.trayIcon]
iconPath = "../res/kasuri.ico"
id = "main"
menuOnLeftClick = true
showMenuOnLeftClick = true
tooltip = "KASURI👘"

[[app.windows]]
title = "KASURI"
label = "main"
width = 800
height = 600
alwaysOnTop = true
backgroundColor = "#000000"
browserExtensionsEnabled = false
center = true
closable = false
contentProtected = true
create = true
decorations = false
devtools = true                  # false
dragDropEnabled = false
focus = true
resizable = false
skipTaskbar = false              # true
visible = false
transparent = true
url = "index.html"

[[app.windows]]
title = "KASURI - Settings"
label = "settings"
alwaysOnTop = true
backgroundColor = "#000000"
browserExtensionsEnabled = false
center = true
closable = true
contentProtected = true
create = false
decorations = false
devtools = true                  # false
dragDropEnabled = false
focus = true
fullscreen = false
height = 600
width = 800
maximizable = true
minimizable = true
resizable = true
skipTaskbar = false
zoomHotkeysEnabled = true
url = "settings.html"


[bundle]
active = true
targets = "nsis"
icon = ["../res/kasuri.ico"]
category = "Utility"
copyright = "© 2025 sabiz"
homepage = "https://github.com/sabiz/KASURI"
shortDescription = "Fuzzy search app launcher"

[plugins]
